### ISSUE TITLE
Нет проверки на некорретное число повторений по умолчанию в конфиге

### ISSUE THREAD

**Issue by olegromashin** [alleksandrgall/metalampBot#20]
Привет. Я буду одним из ревьюеров твоих проектов от лица Metalamp. :)

Сейчас я могу указать 0 или 6 повторений сообщений по умолчанию в конфиге и всё будет работать. Надо это исправить, чтобы указывать можно было от 1 до 5 повторений, как в задании.

**Comment by alleksandrgall** [comment]
Привет, запушил
