### ISSUE TITLE
Слишком маленький таймаут для поллинга

### ISSUE THREAD

**Issue by olegromashin** [alleksandrgall/metalampBot#24]
Сейчас для Телеграма указан слишком маленький таймаут для поллинга метода `getUpdates`. Теряется весь смысл использования этой технологии. Обычно выставляют от 30 до 90 секунд. Можно вынести в конфиг - на твоё усмотрение.

**Comment by alleksandrgall** [comment]
Я запушу в мейн просто? Не думаю что конфиг здесь сильно нужен
